MvcClient/Controllers/AuthController.cs
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcClient.Models.Auth;
using System.Text.Json;
using MvcClient.Views.Auth;

namespace MvcClient.Controllers
{
    public class AuthController : Controller
    {
        private readonly HttpClient _client = new HttpClient();
        private readonly ILogger<AuthController> _logger;
        private readonly JsonSerializerOptions _jsonSerializerOptions = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
        };


        public AuthController(ILogger<AuthController> logger)
        {
            _logger = logger;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Login(
            [Bind("Username, Password")]LoginModel model)
        {
            var requestBody = new StringContent(JsonSerializer.Serialize(model), Encoding.Default, "application/json");
            var response = await _client.PostAsync("https://localhost:5001/api/Auth/login",
                requestBody);
            if (response.StatusCode == HttpStatusCode.OK)
            {
                var contentStream = await response.Content.ReadAsStreamAsync();
                var token = await JsonSerializer.DeserializeAsync<TokenModel>(contentStream, _jsonSerializerOptions);
                CurrentUser.Login(token.Id, model.Username, token.Token);
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction(nameof(Login));
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Register(
            [Bind("Username, Email, Password, PasswordRepeat")] RegisterModel model)
        {
            if (model.Password == model.PasswordRepeat)
            {
                var requestModel = JsonSerializer.Serialize(model);
                var response = await _client.PostAsync("https://localhost:5001/api/Auth/register",
                    new StringContent(requestModel));
                if (response.StatusCode == HttpStatusCode.Created)
                {
                    return RedirectToAction(nameof(Login));
                }
            }
            
            return RedirectToAction(nameof(Register));
        }

        public IActionResult Logout()
        {
            CurrentUser.Logout();
            return RedirectToAction("Index", "Home");
        }
    }
}

MvcClient/Views/Shared/_Layout.cshtml
@using MvcClient.Views.Auth
@using MvcClient.Models.Auth
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Фильмы</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Фильмы</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @if (!@CurrentUser.Authorized)
            {
                <a class="navbar-expand" asp-controller="Auth" asp-action="Login">Войти</a>
                <a class="navbar-expand" asp-controller="Auth" asp-action="Register">Зарегистрироваться</a>
            }
            else
            {
                <p class="navbar-text">@CurrentUser.Username</p>
                <a class="navbar-expand" asp-controller="Auth" asp-action="Logout">Выйти</a>
            }
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>